CTFd/CTFd/forms/config.py
from wtforms import BooleanField, FileField, SelectField, StringField, TextAreaField
from wtforms.fields.html5 import IntegerField, URLField
from wtforms.widgets.html5 import NumberInput

from CTFd.constants.config import (
    AccountVisibilityTypes,
    ChallengeVisibilityTypes,
    RegistrationVisibilityTypes,
    ScoreVisibilityTypes,
)
from CTFd.constants.languages import SELECT_LANGUAGE_LIST
from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField
from CTFd.utils.csv import get_dumpable_tables


class ResetInstanceForm(BaseForm):
    accounts = BooleanField(
        "Accounts",
        description="Deletes all user and team accounts and their associated information",
    )
    submissions = BooleanField(
        "Submissions",
        description="Deletes all records that accounts gained points or took an action",
    )
    challenges = BooleanField(
        "Challenges", description="Deletes all challenges and associated data"
    )
    pages = BooleanField(
        "Pages", description="Deletes all pages and their associated files"
    )
    notifications = BooleanField(
        "Notifications", description="Deletes all notifications"
    )
    submit = SubmitField("Reset CTF")


class AccountSettingsForm(BaseForm):
    domain_whitelist = StringField(
        "Email Domain Allowlist",
        description="Comma-seperated list of allowable email domains which users can register under (e.g. examplectf.com, example.com, *.example.com)",
    )
    team_creation = SelectField(
        "Team Creation",
        description="Control whether users can create their own teams (Teams mode only)",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )
    team_size = IntegerField(
        widget=NumberInput(min=0),
        description="Maximum number of users per team (Teams mode only)",
    )
    num_teams = IntegerField(
        "Maximum Number of Teams",
        widget=NumberInput(min=0),
        description="Maximum number of teams allowed to register with this CTF (Teams mode only)",
    )
    num_users = IntegerField(
        "Maximum Number of Users",
        widget=NumberInput(min=0),
        description="Maximum number of user accounts allowed to register with this CTF",
    )
    verify_emails = SelectField(
        "Verify Emails",
        description="Control whether users must confirm their email addresses before playing",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="false",
    )
    team_disbanding = SelectField(
        "Team Disbanding",
        description="Control whether team captains are allowed to disband their own teams",
        choices=[
            ("inactive_only", "Enabled for Inactive Teams"),
            ("disabled", "Disabled"),
        ],
        default="inactive_only",
    )
    name_changes = SelectField(
        "Name Changes",
        description="Control whether users and teams can change their names",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )
    incorrect_submissions_per_min = IntegerField(
        "Incorrect Submissions per Minute",
        widget=NumberInput(min=1),
        description="Number of submissions allowed per minute for flag bruteforce protection (default: 10)",
    )

    submit = SubmitField("Update")


class ExportCSVForm(BaseForm):
    table = SelectField("Database Table", choices=get_dumpable_tables())
    submit = SubmitField("Download CSV")


class ImportCSVForm(BaseForm):
    csv_type = SelectField(
        "CSV Type",
        choices=[("users", "Users"), ("teams", "Teams"), ("challenges", "Challenges")],
        description="Type of CSV data",
    )
    csv_file = FileField("CSV File", description="CSV file contents")


class SocialSettingsForm(BaseForm):
    social_shares = SelectField(
        "Social Shares",
        description="Enable or Disable social sharing links for challenge solves",
        choices=[("true", "Enabled"), ("false", "Disabled")],
        default="true",
    )
    submit = SubmitField("Update")


class LegalSettingsForm(BaseForm):
    tos_url = URLField(
        "Terms of Service URL",
        description="External URL to a Terms of Service document hosted elsewhere",
    )
    tos_text = TextAreaField(
        "Terms of Service",
        description="Text shown on the Terms of Service page",
    )
    privacy_url = URLField(
        "Privacy Policy URL",
        description="External URL to a Privacy Policy document hosted elsewhere",
    )
    privacy_text = TextAreaField(
        "Privacy Policy",
        description="Text shown on the Privacy Policy page",
    )
    submit = SubmitField("Update")


class VisibilitySettingsForm(BaseForm):
    challenge_visibility = SelectField(
        "Challenge Visibility",
        description="Control whether users must be logged in to see challenges",
        choices=[
            (ChallengeVisibilityTypes.PUBLIC, "Public"),
            (ChallengeVisibilityTypes.PRIVATE, "Private"),
            (ChallengeVisibilityTypes.ADMINS, "Admins Only"),
        ],
        default=ChallengeVisibilityTypes.PRIVATE,
    )
    account_visibility = SelectField(
        "Account Visibility",
        description="Control whether accounts (users & teams) are shown to everyone, only to authenticated users, or only to admins",
        choices=[
            (AccountVisibilityTypes.PUBLIC, "Public"),
            (AccountVisibilityTypes.PRIVATE, "Private"),
            (AccountVisibilityTypes.ADMINS, "Admins Only"),
        ],
        default=AccountVisibilityTypes.PUBLIC,
    )
    score_visibility = SelectField(
        "Score Visibility",
        description="Control whether solves/score are shown to the public, to logged in users, hidden to all non-admins, or only shown to admins",
        choices=[
            (ScoreVisibilityTypes.PUBLIC, "Public"),
            (ScoreVisibilityTypes.PRIVATE, "Private"),
            (ScoreVisibilityTypes.HIDDEN, "Hidden"),
            (ScoreVisibilityTypes.ADMINS, "Admins Only"),
        ],
        default=ScoreVisibilityTypes.PUBLIC,
    )
    registration_visibility = SelectField(
        "Registration Visibility",
        description="Control whether registration is enabled for everyone or disabled",
        choices=[
            (RegistrationVisibilityTypes.PUBLIC, "Public"),
            (RegistrationVisibilityTypes.PRIVATE, "Private"),
            (RegistrationVisibilityTypes.MLC, "MajorLeagueCyber Only"),
        ],
        default=RegistrationVisibilityTypes.PUBLIC,
    )


class LocalizationForm(BaseForm):
    default_locale = SelectField(
        "Default Language",
        description="Language to use if a user does not specify a language in their account settings. By default, CTFd will auto-detect the user's preferred language.",
        choices=SELECT_LANGUAGE_LIST,
    )

CTFd/CTFd/forms/submissions.py
from wtforms import SelectField, StringField
from wtforms.validators import InputRequired

from CTFd.forms import BaseForm
from CTFd.forms.fields import SubmitField


class SubmissionSearchForm(BaseForm):
    field = SelectField(
        "Search Field",
        choices=[
            ("provided", "Provided"),
            ("id", "ID"),
            ("account_id", "Account ID"),
            ("challenge_id", "Challenge ID"),
            ("challenge_name", "Challenge Name"),
        ],
        default="provided",
        validators=[InputRequired()],
    )
    q = StringField("Parameter", validators=[InputRequired()])
    submit = SubmitField("Search")

CTFd/CTFd/admin/__init__.py
import csv  # noqa: I001
import datetime
import os
from io import StringIO

from flask import Blueprint, abort
from flask import current_app as app
from flask import (
    jsonify,
    redirect,
    render_template,
    render_template_string,
    request,
    send_file,
    url_for,
)

admin = Blueprint("admin", __name__)

# isort:imports-firstparty
from CTFd.admin import challenges  # noqa: F401,I001
from CTFd.admin import notifications  # noqa: F401,I001
from CTFd.admin import pages  # noqa: F401,I001
from CTFd.admin import scoreboard  # noqa: F401,I001
from CTFd.admin import statistics  # noqa: F401,I001
from CTFd.admin import submissions  # noqa: F401,I001
from CTFd.admin import teams  # noqa: F401,I001
from CTFd.admin import users  # noqa: F401,I001
from CTFd.cache import (
    cache,
    clear_all_team_sessions,
    clear_all_user_sessions,
    clear_challenges,
    clear_config,
    clear_pages,
    clear_standings,
)
from CTFd.models import (
    Awards,
    Challenges,
    Configs,
    Notifications,
    Pages,
    Solves,
    Submissions,
    Teams,
    Tracking,
    Unlocks,
    Users,
    db,
)
from CTFd.utils import config as ctf_config
from CTFd.utils import get_app_config, get_config, set_config
from CTFd.utils.csv import dump_csv, load_challenges_csv, load_teams_csv, load_users_csv
from CTFd.utils.decorators import admins_only
from CTFd.utils.exports import background_import_ctf
from CTFd.utils.exports import export_ctf as export_ctf_util
from CTFd.utils.security.auth import logout_user
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import is_admin


@admin.route("/admin", methods=["GET"])
def view():
    if is_admin():
        return redirect(url_for("admin.statistics"))
    return redirect(url_for("auth.login"))


@admin.route("/admin/plugins/<plugin>", methods=["GET", "POST"])
@admins_only
def plugin(plugin):
    if request.method == "GET":
        plugins_path = os.path.join(app.root_path, "plugins")

        config_html_plugins = [
            name
            for name in os.listdir(plugins_path)
            if os.path.isfile(os.path.join(plugins_path, name, "config.html"))
        ]

        if plugin in config_html_plugins:
            config_html = open(
                os.path.join(app.root_path, "plugins", plugin, "config.html")
            ).read()
            return render_template_string(config_html)
        abort(404)
    elif request.method == "POST":
        for k, v in request.form.items():
            if k == "nonce":
                continue
            set_config(k, v)
        with app.app_context():
            clear_config()
        return "1"


@admin.route("/admin/import", methods=["GET", "POST"])
@admins_only
def import_ctf():
    if request.method == "GET":
        start_time = cache.get("import_start_time")
        end_time = cache.get("import_end_time")
        import_status = cache.get("import_status")
        import_error = cache.get("import_error")
        return render_template(
            "admin/import.html",
            start_time=start_time,
            end_time=end_time,
            import_status=import_status,
            import_error=import_error,
        )
    elif request.method == "POST":
        backup = request.files["backup"]
        background_import_ctf(backup)
        return redirect(url_for("admin.import_ctf"))


@admin.route("/admin/export", methods=["GET", "POST"])
@admins_only
def export_ctf():
    backup = export_ctf_util()
    ctf_name = ctf_config.ctf_name()
    day = datetime.datetime.now().strftime("%Y-%m-%d_%T")
    full_name = "{}.{}.zip".format(ctf_name, day)
    return send_file(
        backup, cache_timeout=-1, as_attachment=True, attachment_filename=full_name
    )


@admin.route("/admin/import/csv", methods=["POST"])
@admins_only
def import_csv():
    csv_type = request.form["csv_type"]
    # Try really hard to load data in properly no matter what nonsense Excel gave you
    raw = request.files["csv_file"].stream.read()
    try:
        csvdata = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        try:
            csvdata = raw.decode("cp1252")
        except UnicodeDecodeError:
            csvdata = raw.decode("latin-1")
    csvfile = StringIO(csvdata)

    loaders = {
        "challenges": load_challenges_csv,
        "users": load_users_csv,
        "teams": load_teams_csv,
    }

    loader = loaders[csv_type]
    reader = csv.DictReader(csvfile)
    success = loader(reader)
    if success is True:
        return redirect(url_for("admin.config"))
    else:
        return jsonify(success), 500


@admin.route("/admin/export/csv")
@admins_only
def export_csv():
    table = request.args.get("table")

    output = dump_csv(name=table)

    return send_file(
        output,
        as_attachment=True,
        max_age=-1,
        download_name="{name}-{table}.csv".format(
            name=ctf_config.ctf_name(), table=table
        ),
    )


@admin.route("/admin/config", methods=["GET", "POST"])
@admins_only
def config():
    # Clear the config cache so that we don't get stale values
    clear_config()

    configs = Configs.query.all()
    configs = {c.key: get_config(c.key) for c in configs}

    themes = ctf_config.get_themes()

    # Remove current theme but ignore failure
    try:
        themes.remove(get_config("ctf_theme"))
    except ValueError:
        pass

    force_html_sanitization = get_app_config("HTML_SANITIZATION")

    return render_template(
        "admin/config.html",
        themes=themes,
        **configs,
        force_html_sanitization=force_html_sanitization
    )


@admin.route("/admin/reset", methods=["GET", "POST"])
@admins_only
def reset():
    if request.method == "POST":
        require_setup = False
        logout = False
        next_url = url_for("admin.statistics")

        data = request.form

        if data.get("pages"):
            _pages = Pages.query.all()
            for p in _pages:
                for f in p.files:
                    delete_file(file_id=f.id)

            Pages.query.delete()

        if data.get("notifications"):
            Notifications.query.delete()

        if data.get("challenges"):
            _challenges = Challenges.query.all()
            for c in _challenges:
                for f in c.files:
                    delete_file(file_id=f.id)
            Challenges.query.delete()

        if data.get("accounts"):
            Users.query.delete()
            Teams.query.delete()
            require_setup = True
            logout = True

        if data.get("submissions"):
            Solves.query.delete()
            Submissions.query.delete()
            Awards.query.delete()
            Unlocks.query.delete()
            Tracking.query.delete()

        if data.get("user_mode") == "users":
            db.session.query(Users).update({Users.team_id: None})
            Teams.query.delete()

            clear_all_user_sessions()
            clear_all_team_sessions()

        if require_setup:
            set_config("setup", False)
            cache.clear()
            logout_user()
            next_url = url_for("views.setup")

        db.session.commit()

        clear_pages()
        clear_standings()
        clear_challenges()
        clear_config()

        if logout is True:
            cache.clear()
            logout_user()

        db.session.close()
        return redirect(next_url)

    return render_template("admin/reset.html")

CTFd/CTFd/api/v1/statistics/__init__.py
from flask_restx import Namespace

statistics_namespace = Namespace(
    "statistics", description="Endpoint to retrieve Statistics"
)

# isort:imports-firstparty
from CTFd.api.v1.statistics import challenges  # noqa: F401,I001
from CTFd.api.v1.statistics import scores  # noqa: F401
from CTFd.api.v1.statistics import submissions  # noqa: F401
from CTFd.api.v1.statistics import teams  # noqa: F401
from CTFd.api.v1.statistics import users  # noqa: F401

CTFd/CTFd/utils/config/__init__.py
import os
import time

from flask import current_app as app

from CTFd.constants.themes import DEFAULT_THEME
from CTFd.utils import get_app_config, get_config
from CTFd.utils.modes import TEAMS_MODE, USERS_MODE


def ctf_name():
    name = get_config("ctf_name")
    return name if name else "CTFd"


def user_mode():
    return get_config("user_mode")


def is_users_mode():
    return user_mode() == USERS_MODE


def is_teams_mode():
    return user_mode() == TEAMS_MODE


def ctf_logo():
    return get_config("ctf_logo")


def ctf_theme():
    theme = get_config("ctf_theme")
    return theme if theme else ""


def ctf_theme_candidates():
    yield ctf_theme()
    if bool(get_app_config("THEME_FALLBACK")):
        yield DEFAULT_THEME


def is_setup():
    return bool(get_config("setup")) is True


def is_scoreboard_frozen():
    freeze = get_config("freeze")

    if freeze:
        freeze = int(freeze)
        if freeze < time.time():
            return True

    return False


def can_send_mail():
    return mailserver() or mailgun()


def get_mail_provider():
    mail_provider = app.config.get("MAIL_PROVIDER")
    if mail_provider:
        return mail_provider
    if get_config("mail_server") and get_config("mail_port"):
        return "smtp"
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return "mailgun"
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return "smtp"
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return "mailgun"


def mailgun():
    if app.config.get("MAILGUN_API_KEY") and app.config.get("MAILGUN_BASE_URL"):
        return True
    if get_config("mailgun_api_key") and get_config("mailgun_base_url"):
        return True
    return False


def mailserver():
    if app.config.get("MAIL_SERVER") and app.config.get("MAIL_PORT"):
        return True
    if get_config("mail_server") and get_config("mail_port"):
        return True
    return False


def get_themes():
    dir = os.path.join(app.root_path, "themes")
    return [
        name
        for name in os.listdir(dir)
        if os.path.isdir(os.path.join(dir, name)) and name != "admin"
    ]

CTFd/CTFd/themes/admin/templates/config.html
{% extends "admin/base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{{ url_for('views.themes', theme='admin', path='css/codemirror.css') }}">
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Configuration</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-3">
			<ul id="config-sidebar" class="nav nav-pills flex-column">

				<li class="nav-item">
					<a class="nav-link rounded-0 py-1 active" href="#general" role="tab" data-toggle="tab">
						<i class="fa fa-gear action-icon"></i>General
					</a>
				</li>
				<!-- Appearance -->
				<small class="section-title">Appearance</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#logo" role="tab" data-toggle="tab">
						<i class="fa fa-signature action-icon"></i>Logo
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#theme" role="tab" data-toggle="tab">
						<i class="fa fa-brush action-icon"></i>Theme
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#localization" role="tab" data-toggle="tab">
						<i class="fa fa-language action-icon"></i>Localization
					</a>
				</li>
				<!-- Access -->
				<small class="section-title">Access</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#visibility" role="tab" data-toggle="tab">
						<i class="fa fa-eye action-icon"></i>Visibility
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#ctftime" role="tab" data-toggle="tab">
						<i class="fa fa-stopwatch action-icon"></i>Start and End Time
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#pause" role="tab" data-toggle="tab">
						<i class="fa fa-pause action-icon"></i>Pause
					</a>
				</li>

				<!-- Users -->
				<small class="section-title">Users</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#accounts" role="tab" data-toggle="tab">
						<i class="fa fa-users action-icon"></i>Accounts
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#brackets" role="tab" data-toggle="tab">
						<i class="fa fa-chart-line action-icon"></i>Scoreboard Brackets
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#fields" role="tab" data-toggle="tab">
						<i class="fa fa-fingerprint action-icon"></i>Custom Fields
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#registration_code" role="tab" data-toggle="tab">
						<i class="fa fa-user-lock action-icon"></i>Registration Code
					</a>
				</li>

				<small class="section-title">Backup</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#backup" role="tab" data-toggle="tab">
						<i class="fa fa-file-import action-icon"></i>Import & Export
					</a>
				</li>

				<!-- Security -->
				<small class="section-title">Security</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#sanitize" role="tab" data-toggle="tab">
						<i class="fa fa-shield-halved action-icon"></i>Sanitize
					</a>
				</li>

				<!-- Pages -->
				<small class="section-title">Pages</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#legal" role="tab" data-toggle="tab">
						<i class="fa fa-scale-balanced action-icon"></i>Legal
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#robots" role="tab" data-toggle="tab">
						<i class="fa fa-robot action-icon"></i>Robots.txt
					</a>
				</li>
				
				<!-- Integrations -->
				<small class="section-title">Integrations</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#email" role="tab" data-toggle="tab">
						<i class="fa fa-envelope action-icon"></i>Email Notifications
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#social" role="tab" data-toggle="tab">
						<i class="fa fa-share-nodes action-icon"></i>Social Sharing
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1s" href="#mlc" role="tab" data-toggle="tab">
						<i class="fa fa-network-wired action-icon"></i>MajorLeagueCyber
					</a>
				</li>
				
				<!-- Plugins -->
				{% set plugins = get_configurable_plugins() %}
				{% if plugins %}
					<small class="section-title">Plugins</small>
					{% for plugin in plugins %}
						{% if plugin.config %}
							<li class="nav-item">
								<a class="nav-link rounded-0 py-1" href="#plugin_{{loop.index}}" role="tab" data-toggle="tab">
									<i class="fa-solid fa-puzzle-piece action-icon"></i>{{ plugin.name }}
								</a>
							</li>
						{% elif plugin.route %}
							<li class="nav-item">
								<a class="nav-link rounded-0 py-1" href="{{ plugin.route }}" target="_blank">
									<i class="fa-solid fa-puzzle-piece action-icon"></i>{{ plugin.name }} <i class="fa-solid fa-arrow-up-right-from-square fa-xs"></i>
								</a>
							</li>
						{% endif %}
					{% endfor %}
				{% endif %}

				<!-- Reset -->
				<small class="section-title">Danger zone</small>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="#usermode" role="tab" data-toggle="tab">
						<i class="fa fa-people-arrows action-icon"></i>User Mode
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link rounded-0 py-1" href="{{ url_for('admin.reset') }}" role="tab">
						<i class="fa fa-trash-can action-icon"></i>Reset
					</a>
				</li>
			</ul>
		</div>
		<div class="col-md-9">
			{% for error in errors %}
				<div class="alert alert-danger alert-dismissable" role="alert">
					<span class="sr-only">Error:</span>
					{{ error }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
				</div>
			{% endfor %}

			<div class="tab-content">
				{% include "admin/configs/general.html" %}

				<!-- Appearance -->

				{% include "admin/configs/logo.html" %}

				{% include "admin/configs/theme.html" %}

				{% include "admin/configs/localization.html" %}

				<!-- Access -->

				{% include "admin/configs/visibility.html" %}

				{% include "admin/configs/time.html" %}

				{% include "admin/configs/pause.html" %}

				<!-- Users -->

				{% include "admin/configs/accounts.html" %}

				{% include "admin/configs/usermode.html" %}

				{% include "admin/configs/brackets.html" %}

				{% include "admin/configs/fields.html" %}

				{% include "admin/configs/registration_code.html" %}

				<!-- Security -->

				{% include "admin/configs/backup.html" %}

				{% include "admin/configs/sanitize.html" %}

				<!-- Pages -->

				{% include "admin/configs/legal.html" %}

				{% include "admin/configs/robots.html" %}

				<!-- Integrations -->

				{% include "admin/configs/email.html" %}

				{% include "admin/configs/social.html" %}

				{% include "admin/configs/mlc.html" %}

				<!-- Plugins -->
				
				{% if plugins %}
					{% for plugin in plugins %}
						{% if plugin.config %}
							<div role="tabpanel" class="tab-pane config-section" id="plugin_{{loop.index}}">
								{% include plugin.config %}
							</div>
						{% endif %}
					{% endfor %}
				{% endif %}
				<!-- Danger zone -->
				<!-- reset.html is top-level so no need to include -->
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	{{ Assets.js("assets/js/pages/configs.js", theme="admin") }}
{% endblock %}

CTFd/CTFd/themes/admin/templates/import.html
{% extends "admin/base.html" %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Import Status</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			<p>
				<b>Start Time:</b> <span id="start-time">{{ start_time }}</span>
			</p>
			{% if end_time %}
			<p>
				<b>End Time:</b> <span id="end-time">{{ end_time }}</span>
			</p>
			{% endif %}
			{% if import_error %}
			<p>
				<b>Import Error:</b> {{ import_error }}
			</p>
			<div class="alert alert-danger" role="alert">
				An error occurred during the import. Please try again. 
			</div>
			{% else %}
			<p>
				<b>Current Status:</b> {{ import_status }}
			</p>
			<div class="alert alert-secondary" role="alert">
				Page will redirect upon completion. Refresh page to get latest status.<br>
				Page will automatically refresh every 5 seconds.
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script>
	// Reload every 5 seconds to poll import status
	setTimeout(function(){
		window.location.reload();
	}, 5000);
	
	let start_time = "{{ start_time | tojson }}";
	let end_time = "{{ end_time | tojson }}";
	let start = document.getElementById("start-time");
	start.innerText = new Date(parseInt(start_time) * 1000);
	
	if (end_time !== "null") {
		let end = document.getElementById("end-time");
		end.innerText = new Date(parseInt(end_time) * 1000);
	}
</script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/integrations.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-5 text-center">
            <h5>Integration enabled!</h5>
            <p>You may now close this tab.</p>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    localStorage.removeItem('integrations');
    var params = {};
    var pieces = window.location.search
        .substr(1)
        .split("&");
    for (let i = 0; i < pieces.length; i++) {
        var tmp = pieces[i].split("=");
        params[tmp[0]] = tmp[1];
    }
    localStorage.setItem('integrations', JSON.stringify(params));
</script>
{% endblock %}

CTFd/CTFd/themes/admin/templates/page.html
{% extends "admin/base.html" %}

{% block content %}
	<div class="container">
		{{ content | safe }}
	</div>
{% endblock %}